version: '3'

services:
  # Backend API service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5500:5500"
    environment:
      - NODE_ENV=production
      - PORT=5500
      - HOST=0.0.0.0
      - DATABASE_URL=postgres://postgres:password@postgres:5432/csemotors
      - JWT_SECRET=your_jwt_secret_here
      - SESSION_SECRET=your_session_secret_here
    depends_on:
      - postgres
    networks:
      - app-network
    volumes:
      - ./public:/app/public

  # Frontend service (optional for development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - app-network

  # Database service
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=csemotors
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: